In [1]:
from collections import Counter

# 샘플 코퍼스
corpus = ["자연어 처리는 재미있다.", "자연어 처리는 컴퓨터 과학의 한 분야다.", "데이터 분석은 자연어 처리와 밀접하다."]

# 단어 단위로 코퍼스를 분리
tokenized_corpus = [sentence.split() for sentence in corpus]
flat_tokens = [word for sentence in tokenized_corpus for word in sentence]

# 단어 빈도 분석
word_freq = Counter(flat_tokens)
print("단어 빈도 분석 결과:", word_freq)

단어 빈도 분석 결과: Counter({'자연어': 3, '처리는': 2, '재미있다.': 1, '컴퓨터': 1, '과학의': 1, '한': 1, '분야다.': 1, '데이터': 1, '분석은': 1, '처리와': 1, '밀접하다.': 1})


In [2]:
from nltk.corpus import wordnet # 영어 어휘/의미 사전

# Synset 사용 예제
word = "bank"
synsets = wordnet.synsets(word) # synsets(word) : word에 해당하는 모든 의미 리스트 반환
for syn in synsets:
    print(f"뜻: {syn.definition()}")

뜻: sloping land (especially the slope beside a body of water)
뜻: a financial institution that accepts deposits and channels the money into lending activities
뜻: a long ridge or pile
뜻: an arrangement of similar objects in a row or in tiers
뜻: a supply or stock held in reserve for future use (especially in emergencies)
뜻: the funds held by a gambling house or the dealer in some gambling games
뜻: a slope in the turn of a road or track; the outside is higher than the inside in order to reduce the effects of centrifugal force
뜻: a container (usually with a slot in the top) for keeping money at home
뜻: a building in which the business of banking transacted
뜻: a flight maneuver; aircraft tips laterally about its longitudinal axis (especially in turning)
뜻: tip laterally
뜻: enclose with a bank
뜻: do business with a bank or keep an account at a bank
뜻: act as the banker in a game or in gambling
뜻: be in the banking business
뜻: put into a bank account
뜻: cover with ashes so to control the rate 

In [3]:
import re

# 원시 텍스트
raw_text = "Hello!!! 자연어 처리 is FUN.   Do you agree? :)"

# 불필요한 기호 제거(정규표현식 \w: 문자,숫자,_ / \s: 공백)
clean_text = re.sub(r"[^\w\s]", "", raw_text)

# 소문자 변환
clean_text = clean_text.lower()

# 공백 제거
clean_text = " ".join(clean_text.split())

print("처리된 텍스트:", clean_text)

처리된 텍스트: hello 자연어 처리 is fun do you agree


In [4]:
from nltk.tokenize import sent_tokenize # 문장 단위 분리해주는 토크나이저(!, ., ? 기준)

text = "자연어 처리는 재미있다! 하지만 배우기는 어렵다. Python으로 가능합니다."
print(sent_tokenize(text))

['자연어 처리는 재미있다!', '하지만 배우기는 어렵다.', 'Python으로 가능합니다.']


In [5]:
from nltk.tokenize import word_tokenize
import string

# 원시 텍스트
raw_text = "자연어 처리는 데이터 과학의 한 분야다! 여러 전처리가 필요하다."

# 특수문자 제거
clean_text = raw_text.translate(str.maketrans("", "", string.punctuation))

# 숫자 제거
clean_text = re.sub(r"\\d+", "", clean_text)

# 불용어 제거 (NLTK stopwords는 한국어를 지원하지 않아 직접 리스트 정의)
korean_stopwords = {"은", "는", "이", "가", "을", "를", "의", "에", "와", "과", "한", "및", "여러"}
# stop_words = set(stopwords.words("korean"))  # NLTK에서 제공하는 한국어 불용어 리스트 사용 가능
tokens = word_tokenize(clean_text)
filtered_tokens = [word for word in tokens if word not in korean_stopwords]

print("전처리 결과:", filtered_tokens)

전처리 결과: ['자연어', '처리는', '데이터', '과학의', '분야다', '전처리가', '필요하다']


In [6]:
import nltk

nltk.download('punkt')  # 토크나이저를 위한 데이터 다운로드
nltk.download('stopwords')  # 불용어를 위한 데이터 다운로드
nltk.download('wordnet')  # WordNet을 위한 데이터 다운로드

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\uk\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\uk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\uk\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [7]:
from konlpy.tag import Okt

# 텍스트
text = "자연어 처리는 정말 재미있다!"

# 형태소 분석
okt = Okt()
morphs = okt.morphs(text) # 최소 의미 단위 리스트 분리
pos = okt.pos(text)       # (형태소,품사) 튜플 리스트로 품사 태깅 작업

print("형태소 분석 결과:", morphs)
print("품사 태깅 결과:", pos)

형태소 분석 결과: ['자연어', '처리', '는', '정말', '재미있다', '!']
품사 태깅 결과: [('자연어', 'Noun'), ('처리', 'Noun'), ('는', 'Josa'), ('정말', 'Noun'), ('재미있다', 'Adjective'), ('!', 'Punctuation')]


In [8]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 샘플 데이터
corpus = ["자연어 처리는 재미있다.", "자연어 처리는 어렵다.", "데이터는 유용하다."]

# Bag-of-Words
vectorizer = CountVectorizer()  # BoW 벡터라이저 생성
bow = vectorizer.fit_transform(corpus)  # 단어사전 학습(생성) + BoW 벡터로 변환 (희소행렬)
print(bow)
print("Bag-of-Words:\\n", bow.toarray())    #밀집 배열 형태로 변환해서 출력

# TF-IDF
tfidf = TfidfVectorizer()   # TF-IDF 벡터라이저 생성
tfidf_matrix = tfidf.fit_transform(corpus)  # 단어사전 학습(생성) + TF-IDF 벡터로 변환 (희소행렬)
print("TF-IDF:\\n", tfidf_matrix.toarray()) # TF-IDF 결과를 배열로 변환해서 출력

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (3, 6)>
  Coords	Values
  (0, 3)	1
  (0, 5)	1
  (0, 4)	1
  (1, 3)	1
  (1, 5)	1
  (1, 1)	1
  (2, 0)	1
  (2, 2)	1
Bag-of-Words:\n [[0 0 0 1 1 1]
 [0 1 0 1 0 1]
 [1 0 1 0 0 0]]
TF-IDF:\n [[0.         0.         0.         0.51785612 0.68091856 0.51785612]
 [0.         0.68091856 0.         0.51785612 0.         0.51785612]
 [0.70710678 0.         0.70710678 0.         0.         0.        ]]


In [9]:
# 샘플 텍스트
text = "자연어 처리는 재미있다. 자연어는 어렵지만 재미있다."

# 단어 빈도 계산
from collections import Counter
words = text.split()
word_count = Counter(words)

# 문장 길이 계산
sentences = text.split(". ")
sentence_lengths = [len(sentence.split()) for sentence in sentences]

print("단어 빈도:", word_count)
print("문장 길이:", sentence_lengths)

단어 빈도: Counter({'재미있다.': 2, '자연어': 1, '처리는': 1, '자연어는': 1, '어렵지만': 1})
문장 길이: [3, 3]


In [10]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 임의의 단어 벡터
word1 = np.array([[1, 2, 3]])
word2 = np.array([[2, 3, 4]])

# 코사인 유사도 계산
similarity = cosine_similarity(word1, word2)
print("코사인 유사도:", similarity[0][0])

코사인 유사도: 0.9925833339709303


In [11]:
from konlpy.tag import Okt

# 텍스트 데이터
text = "자연어 처리는 재미있다."

# 형태소 분석
okt = Okt()
morphs = okt.morphs(text)
print("형태소 분석 결과:", morphs)

형태소 분석 결과: ['자연어', '처리', '는', '재미있다', '.']


In [12]:
from sklearn.feature_extraction.text import CountVectorizer

# 문장 데이터
corpus = ["자연어 처리는 재미있다.", "Python으로 가능하다."]

# BoW 벡터화
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print("BoW 벡터화 결과:\\n", X.toarray())
print("단어 사전:", vectorizer.vocabulary_)

BoW 벡터화 결과:\n [[0 0 1 1 1]
 [1 1 0 0 0]]
단어 사전: {'자연어': 2, '처리는': 4, '재미있다': 3, 'python으로': 0, '가능하다': 1}


In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 문장 데이터
corpus = ["자연어 처리는 재미있다.", "Python으로 가능하다."]

# TF-IDF 벡터화
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print("TF-IDF 결과:\\n", X.toarray())
print("단어 사전:", vectorizer.vocabulary_)

TF-IDF 결과:\n [[0.         0.         0.57735027 0.57735027 0.57735027]
 [0.70710678 0.70710678 0.         0.         0.        ]]
단어 사전: {'자연어': 2, '처리는': 4, '재미있다': 3, 'python으로': 0, '가능하다': 1}


In [18]:
import sys
!{sys.executable} -m pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ------ --------------------------------- 3.9/24.4 MB 29.4 MB/s eta 0:00:01
   ------------------- -------------------- 12.1/24.4 MB 35.9 MB/s eta 0:00:01
   -------------------------------------- - 23.3/24.4 MB 43.4 MB/s eta 0:00:01
   ---------------------------------------- 24.4/24.4 MB 37.7 MB/s  0:00:00


In [ ]:
from gensim.models import Word2Vec

# 샘플 문장
sentences = [["자연어", "처리", "재미있다"], ["Python", "가능하다"]]

# Word2Vec 모델 학습
model = Word2Vec(
    sentences,          # 토큰화된 문장 (2차원)
    vector_size=100,    # 단어 벡터 차원 수 (100차원)
    window=3,           # 주변 문맥 좌우 3개
    min_count=1,        # 최소 등장 횟수 1 이상인 단어만 사전에 포함
    sg=0                # 0=CBOW(주변 -> 주심 단어 예측), 1 = Skip-gram(중심 -> 주변 단어 예측)
)

# 단어 벡터 확인 : 학습된 '자연어' 임배딩 벡터(길이 = 100)
print("단어 '자연어'의 벡터:", model.wv["자연어"])

단어 '자연어'의 벡터: [-0.00713902  0.00124103 -0.00717672 -0.00224462  0.0037193   0.00583312
  0.00119818  0.00210273 -0.00411039  0.00722533 -0.00630704  0.00464722
 -0.00821997  0.00203647 -0.00497705 -0.00424769 -0.00310898  0.00565521
  0.0057984  -0.00497465  0.00077333 -0.00849578  0.00780981  0.00925729
 -0.00274233  0.00080022  0.00074665  0.00547788 -0.00860608  0.00058446
  0.00686942  0.00223159  0.00112468 -0.00932216  0.00848237 -0.00626413
 -0.00299237  0.00349379 -0.00077263  0.00141129  0.00178199 -0.0068289
 -0.00972481  0.00904058  0.00619805 -0.00691293  0.00340348  0.00020606
  0.00475375 -0.00711994  0.00402695  0.00434743  0.00995737 -0.00447374
 -0.00138926 -0.00731732 -0.00969783 -0.00908026 -0.00102275 -0.00650329
  0.00484973 -0.00616403  0.00251919  0.00073944 -0.00339215 -0.00097922
  0.00997913  0.00914589 -0.00446183  0.00908303 -0.00564176  0.00593092
 -0.00309722  0.00343175  0.00301723  0.00690046 -0.00237388  0.00877504
  0.00758943 -0.00954765 -0.00800821 -

In [21]:
model.wv.most_similar('자연어', topn=5) # 가장 유사한 단어

[('재미있다', 0.17018885910511017),
 ('Python', 0.004503022879362106),
 ('가능하다', -0.027750348672270775),
 ('처리', -0.04461711645126343)]

In [22]:
import gensim.downloader as api

# 1) 미리 학습된 GloVe 로드 (처음 1번은 다운로드 시간이 걸림)
# 50차원 버전: 가볍고 실습용으로 좋음
glove = api.load("glove-wiki-gigaword-50")

# 2) 단어 벡터 확인 (길이=50)
print("king 벡터 차원:", glove["king"].shape)

# 3) 코사인 유사도
print("similarity(king, queen):", glove.similarity("king", "queen"))
print("similarity(king, banana):", glove.similarity("king", "banana"))

# 4) 가장 비슷한 단어 top-n
print("most_similar('king'):", glove.most_similar("king", topn=5))

# 5) 벡터 연산(관계) 예시: king - man + woman ≈ queen
print(glove.most_similar(positive=["king", "woman"], negative=["man"], topn=5))

[==================================================] 100.0% 66.0/66.0MB downloaded
king 벡터 차원: (50,)
similarity(king, queen): 0.7839043
similarity(king, banana): 0.2207408
most_similar('king'): [('prince', 0.8236179351806641), ('queen', 0.7839043140411377), ('ii', 0.7746230363845825), ('emperor', 0.7736247777938843), ('son', 0.766719400882721)]
[('queen', 0.8523604273796082), ('throne', 0.7664334177970886), ('prince', 0.7592144012451172), ('daughter', 0.7473883628845215), ('elizabeth', 0.7460219860076904)]


In [ ]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

# 1) 예시 문서(문장) 준비
docs = [
    "자연어 처리는 재미있다",
    "파이썬으로 자연어 처리를 할 수 있다",
    "축구 경기는 정말 재미있다",
    "오늘 날씨가 좋다"
]

# 2) Doc2Vec은 문서마다 태그(아이디)가 필요함
tagged_docs = [
    TaggedDocument(words=d.split(), tags=[f"DOC_{i}"])  # 긱 문서를 (토큰리스트, 문서 ID)로 변환
    for i, d in enumerate(docs)
]

# 3) Doc2Vec 모델 학습
model = Doc2Vec(
    documents=tagged_docs,  # 태그가 붙은 문서로 학습
    vector_size=50,   # 문서 벡터 차원
    window=3,         # 문맥 범위
    min_count=1,      # 최소 등장 횟수
    workers=2,        # CPU 쓰레드
    epochs=50         # 학습 반복
)

# 4) 학습된 문서 벡터 확인  (첫번쨰 문서의 벡터 상위 10개)
print("DOC_0 벡터 일부:", model.dv["DOC_0"][:10])

# 5) 특정 문서와 가장 유사한 문서 찾기
print("\nDOC_0와 유사한 문서:")
print(model.dv.most_similar("DOC_0", topn=3))

# 6) 새 문장(학습에 없던 문장)도 벡터로 추정 가능(infer_vector)
new_doc = "자연어 처리는 파이썬으로 가능하다"
new_vec = model.infer_vector(new_doc.split())   # 새로운 문장 문서 벡터로 추정

print("\n새 문장과 유사한 문서:")
print(model.dv.most_similar([new_vec], topn=3))

DOC_0 벡터 일부: [-0.01058207 -0.01189603 -0.01985634  0.01694183  0.00701691  0.00072557
 -0.01981407 -0.01017613 -0.01967002  0.00412226]

DOC_0와 유사한 문서:
[('DOC_1', 0.2878270447254181), ('DOC_2', 0.1307842880487442), ('DOC_3', -0.07168306410312653)]

새 문장과 유사한 문서:
[('DOC_0', 0.10927266627550125), ('DOC_3', 0.03823672607541084), ('DOC_1', 0.025490961968898773)]


In [ ]:
from sklearn.decomposition import LatentDirichletAllocation # 토팍 모델링
from sklearn.feature_extraction.text import CountVectorizer

# 문장 데이터
corpus = ["자연어 처리는 재미있다.", "Python으로 가능하다."]

# BoW 벡터화
vectorizer = CountVectorizer()  # BoW 빈도수 기반 벡터라이저
X = vectorizer.fit_transform(corpus)    # 단어사전 학습(생성) + 희소행렬 생성

# LDA 모델 학습
lda = LatentDirichletAllocation(
    n_components=2, # 찾을 주제 갯수
    random_state=0  # 재현성
)
lda.fit(X)  # BoW행렬로 LDA 학습 (주제-단어 분포 / 문서-주제 분포 추정)

# 주제별 단어 분포
print("주제별 단어 분포:\\n", lda.components_)

주제별 단어 분포:\n [[1.4913572  1.4913572  0.50945773 0.50945773 0.50945773]
 [0.5086428  0.5086428  1.49054227 1.49054227 1.49054227]]


In [27]:
import numpy as np

feature_names = vectorizer.get_feature_names_out()  # Vectiorizer 단어 사전(인덱스 -> 단어 배열)

for topic_idx , topic in enumerate(lda.components_):
    top_idx = topic.argsort()[::-1][:5]             # 가중치가 큰 단어 인덱스를 반환(내림차순 후 상위 5개)
    print(f"Topic {topic_idx}:{[(feature_names[i],topic[i])for i in top_idx]}")

Topic 0:[('python으로', np.float64(1.4913571964571597)), ('가능하다', np.float64(1.491357196456652)), ('자연어', np.float64(0.5094577321201083)), ('처리는', np.float64(0.5094577321189349)), ('재미있다', np.float64(0.5094577321184829))]
Topic 1:[('재미있다', np.float64(1.4905422678815157)), ('처리는', np.float64(1.4905422678810638)), ('자연어', np.float64(1.4905422678798905)), ('가능하다', np.float64(0.5086428035433468)), ('python으로', np.float64(0.5086428035428391))]


In [28]:
from gensim.models import FastText   # 서브워드(n-그램) 기반 단어 임베딩 모델 FastText

# 1) 토큰화된 문장(리스트의 리스트) 준비
sentences = [
    ["자연어", "처리", "재미있다"],                          # 문장1 토큰 리스트
    ["파이썬", "으로", "자연어", "처리", "가능하다"],          # 문장2 토큰 리스트
    ["자연어", "처리", "공부", "하자"]                         # 문장3 토큰 리스트
]

# FastText: 단어를 '문자 n-그램(서브워드)' 조합으로도 표현해 OOV(미등장 단어) 벡터 생성에 강함
model = FastText(      # 2) FastText 학습(훈련)
    sentences,         # 학습 데이터(토큰화된 문장들)
    vector_size=50,    # 단어 벡터 차원 수
    window=3,          # 주변 문맥 범위(좌우 3개)
    min_count=1,       # 최소 등장 횟수(1 이상 단어만 사용)
    sg=1,              # 1=Skip-gram(중심→주변), 0=CBOW(주변→중심)
    min_n=2,           # 서브워드(문자 n-그램) 최소 길이
    max_n=5,           # 서브워드(문자 n-그램) 최대 길이
    epochs=50          # 전체 데이터 반복 학습 횟수
)

# 3) 단어 벡터 확인 : '자연어' 임베딩 벡터(50차원) 중 앞 10개 출력
print("자연어 벡터 일부:", model.wv["자연어"][:10])

# 4) 유사 단어(topn) : 코사인 유사도가 높은 단어 TOP3
print("자연어와 비슷한 단어:", model.wv.most_similar("자연어", topn=3))

# 5) 단어 간 유사도(코사인) : 두 단어 벡터의 코사인 유사도 스칼라 출력
print("similarity(자연어, 처리):", model.wv.similarity("자연어", "처리"))

# 6) OOV 예시: 학습에 없던 단어도 서브워드로 벡터 생성 가능
# "자연어처리" 미등장 단어라도 문자 n-그램으로 벡터 추정(앞 5개 출력)
print("OOV 단어 벡터 생성 가능?", model.wv["자연어처리"][:5])

자연어 벡터 일부: [ 0.00226604 -0.00067321 -0.00597979  0.00056262  0.00244565 -0.00171385
 -0.00238545 -0.00246523  0.00509697 -0.00276196]
자연어와 비슷한 단어: [('처리', 0.05201917141675949), ('파이썬', -0.022671055048704147), ('공부', -0.04659514129161835)]
similarity(자연어, 처리): 0.052019175
OOV 단어 벡터 생성 가능? [ 0.00084895 -0.00255903 -0.00200175  0.00446068 -0.00222416]
