In [ ]:
import numpy as np

In [ ]:
import numpy as np
print(np.__version__)

2.5.1


In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [7]:
print(a.shape)
print(a.size)

(3,)
3


In [8]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [9]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
arr = np.ones((4,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# 표현법
[
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
]

[[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [13]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [16]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


평균 0, 표준편차 1인 정규 분포로 난수를 생성한다.

In [17]:
arr = np.random.randn(2,3)
print(arr)

[[-1.41242991 -0.14926425  0.92835702]
 [-0.64268473  2.0092021   1.68042824]]


In [ ]:
# shape : 배열의 모양

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr.shape)  # (2, 3)

(2, 3)


In [19]:
# dimension : 배열의 차원

print(arr.ndim)

2


In [ ]:
# size : 배열의 사이즈
print(arr.size)

6


In [ ]:
# dype : 배열의 데이터 타입
print(arr.dtype)

int64


In [25]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[::2])

10
[10 30 50]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0,1])
print(arr[2,2])

2
9


In [31]:
arr = np.array(
    [
        [
        [1, 2, 3], 
        [4, 5, 6]
        ], 
        [
        [7, 8, 9], 
        [10, 11, 12]
        ]
    ]
) # 2*2*3

print(arr.shape)
print(arr[1,0,2])

(2, 2, 3)
9


In [34]:
arr = np.array([10, 20, 30, 40, 50])
#([20, 30, 40])
print(arr[1:-1])
# ([10, 20, 30])
print(arr[:3])

[20 30 40]
[10 20 30]


In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1:,:2])

[[4 5]
 [7 8]]


In [44]:
arr = np.array(
    [
        [
            [1, 2, 3], 
            [4, 5, 6]
        ], 
        [
            [7, 8, 9], 
            [10, 11, 12]
         ]
     ]
    )
print(arr.shape)
print(arr[:,1,:2])

(2, 2, 3)
[[ 4  5]
 [10 11]]


In [50]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0,2,4]
print(arr[idx])
print(arr[[0,2,4]])

[10 30 50]
[10 30 50]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [2, 1, 0]
print(arr[rows, cols])


[3 5 7]


In [55]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr>30])

[40 50]


In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[arr>4])

[5 6 7 8 9]


In [61]:
arr1 =np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [63]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1,arr2))

32


In [2]:
# list와 numpy ndarray의 차이
import numpy as np

print([1,2,3]*2)
print(np.array([1, 2, 3])*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2))

32


In [4]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d = np.array([5, 6])
print(np.dot(arr2d, arr1d))

[17 39]


In [6]:
arr2d_1 = np.array([[1, 2], [3, 4]])
arr2d_2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr2d_1,arr2d_2))
# [[1*5 + 2*7, 1*6 + 2*8],
#  [3*5 + 4*7, 3*6 + 4*8]]

[[19 22]
 [43 50]]


In [8]:
print(arr2d_1@arr2d_2)

[[19 22]
 [43 50]]


In [11]:
arr = np.array([1,2,3])
print(arr+10)

[11 12 13]


In [12]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr1d = np.array([1,2,3])
print(arr2d+arr1d)

[[2 4 6]
 [5 7 9]]


In [18]:
arr3d = np.random.rand(3,1,4)
arr2d = np.random.rand(4,4)

result = arr3d + arr2d
print(result.shape)
print(arr3d)
print(arr2d)
print(result)

(3, 4, 4)
[[[0.51485314 0.14689674 0.29094145 0.4111454 ]]

 [[0.24115798 0.54784494 0.31979741 0.57300903]]

 [[0.62086363 0.7547666  0.50927841 0.44278002]]]
[[0.39489095 0.40836302 0.24418327 0.0687993 ]
 [0.58508117 0.57885221 0.00899056 0.72570711]
 [0.96973202 0.45901513 0.72118925 0.85963216]
 [0.99730663 0.30275988 0.18140865 0.61957437]]
[[[0.90974409 0.55525977 0.53512473 0.4799447 ]
  [1.0999343  0.72574896 0.29993201 1.13685251]
  [1.48458516 0.60591187 1.0121307  1.27077756]
  [1.51215977 0.44965662 0.47235011 1.03071977]]

 [[0.63604893 0.95620797 0.56398068 0.64180833]
  [0.82623914 1.12669716 0.32878797 1.29871614]
  [1.21089    1.00686007 1.04098665 1.4326412 ]
  [1.23846461 0.85060482 0.50120606 1.1925834 ]]

 [[1.01575458 1.16312962 0.75346168 0.51157931]
  [1.2059448  1.33361881 0.51826897 1.16848712]
  [1.59059565 1.21378172 1.23046765 1.30241218]
  [1.61817026 1.05752648 0.69068706 1.06235439]]]


In [ ]:

arr2d = np.array([[1,2,3],
                  [4,5,6]])

row = np.array([10,20,30])
col = np.array([[10],
                [20]])

print(arr2d.shape,row.shape,col.shape)

(2, 3) (3,) (2, 1)


In [24]:
print(arr2d+row)
print(arr2d+col)


[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]


In [30]:
arr = np.array([10,20,30])

print(arr>15)
print(arr[arr>15])
print(arr ==20)
print(arr!=20)
print(arr[arr ==20])
print(arr[arr!=20])


[False  True  True]
[20 30]
[False  True False]
[ True False  True]
[20]
[10 30]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])
print(arr1 > arr2)  # [False, False, True]
print(arr1[arr1 > arr2])
print(arr2[arr1 > arr2])

[False False  True]
[3]
[2]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())  # 15
print(arr.max()) #최대값
print(arr.min()) # 최소값
print(arr.mean())   # 평균값
print(arr.std())    # 표준편차
print(arr.var())    # 분산
print(arr.cumsum()) #누계

15
5
1
3.0
1.4142135623730951
2.0
[ 1  3  6 10 15]


In [38]:
# 축을 기준으로 한 연산
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d.shape)
print(arr2d.sum(axis=0)) # 5,7,9
print(arr2d.sum(axis=1)) # 6,15

(2, 3)
[5 7 9]
[ 6 15]


In [46]:
arr = np.array([10, 20, 30, 40])
print(np.mean(arr))  # 25.0

25.0


In [45]:
from scipy import stats

arr = np.array([10, 20, 20, 30, 40])
print(stats.mode(arr))  # Mode: 20

ModeResult(mode=np.int64(20), count=np.int64(2))


In [47]:
print(np.var(arr))

125.0


In [48]:
print(np.std(arr))  # 11.1803

11.180339887498949


In [49]:
print(np.max(arr) - np.min(arr))  # 30

30


In [50]:
arr = np.random.randn(1000)  # 평균 0, 표준편차 1인 정규분포 난수 1000개
print(np.mean(arr), np.std(arr))

0.00011281502551345923 1.0169405731530998


In [51]:
arr = np.random.uniform(0, 1, 1000)  # 0과 1 사이의 균등분포 난수 1000개
print(np.mean(arr), np.std(arr))

0.49434039359081944 0.2874279894030971


- # ndarray정렬

In [53]:
import numpy as np

arr = np.array([30,10,20,40,50])
sorted_arr = np.sort(arr)
print(sorted_arr)
sorted_arr_desc = sorted_arr[::-1]
print(sorted_arr_desc)

[10 20 30 40 50]
[50 40 30 20 10]


In [57]:
arr2d = np.array([[5, 2, 3], [8, 4, 1]])
sorted_arr2d = np.sort(arr2d)
print(sorted_arr2d)

[[2 3 5]
 [1 4 8]]


In [58]:
arr2d = np.array(
    [
        [5, 2, 3], 
        [8, 4, 1]
    ]
                  )

np.sort(arr2d,axis=0)

array([[5, 2, 1],
       [8, 4, 3]])

In [59]:
np.sort(arr2d,axis=1)

array([[2, 3, 5],
       [1, 4, 8]])

In [ ]:
arr = np.array([30, 10, 20])
sorted_indices = np.argsort(arr)
print(sorted_indices)
print(arr[sorted_indices])

[1 2 0]
10


In [64]:
arr2d = np.array(
    [
        [3, 1, 2], 
        [6, 4, 5]
        ]
    )
sorted_indices = np.argsort(arr2d, axis=1)
print(sorted_indices)

[[1 2 0]
 [1 2 0]]


In [65]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)  # [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [70]:
arr1 = np.array([
    [1, 2], 
    [3, 4]
])
arr2 = np.array([
    [5, 6], 
    [7, 8]
])
merged_arr = np.concatenate((arr1,arr2),axis=0)
print(merged_arr,merged_arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


In [71]:
merged_arr = np.concatenate((arr1,arr2),axis=1)
print(merged_arr,merged_arr.shape)

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


In [72]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)

[[1 2 3]
 [4 5 6]]


In [73]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.hstack((arr1, arr2))
print(merged_arr) 

[1 2 3 4 5 6]


In [82]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concat__arr1 = np.concatenate((arr1,arr2))
print("concat_arr = ",concat__arr1)
concat__arr2 = np.concatenate((arr1,arr2))
print("concat_arr = ",concat__arr2)

print()
vs_arr = np.vstack((arr1,arr2))
print("vs_arr = ",vs_arr,vs_arr.shape)
print()
hs_arr = np.hstack((arr1,arr2))
print("hs_arr = ",hs_arr)
print()
stacked_arr = np.stack((arr1, arr2), axis=0)
print("stacked_arr = ",stacked_arr,stacked_arr.shape)
print()
stacked_arr1 = np.stack((arr1, arr2), axis=1)
print("stacked_arr = ",stacked_arr1,stacked_arr1.shape)

concat_arr =  [1 2 3 4 5 6]
concat_arr =  [1 2 3 4 5 6]

vs_arr =  [[1 2 3]
 [4 5 6]] (2, 3)

hs_arr =  [1 2 3 4 5 6]

stacked_arr =  [[1 2 3]
 [4 5 6]] (2, 3)

stacked_arr =  [[1 4]
 [2 5]
 [3 6]] (3, 2)


In [75]:
stacked_arr = np.stack((arr1, arr2), axis=1)
print(stacked_arr)


[[1 4]
 [2 5]
 [3 6]]


In [83]:
import time
size = 1000000
python_list = list(range(size))

start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python 리스트 성능:", time.time() - start_time)

Python 리스트 성능: 0.04617595672607422


In [84]:
import numpy as np
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2
print("NumPy 배열 성능:", time.time() - start_time)

NumPy 배열 성능: 0.002391815185546875
