In [1]:
import torch

# 텐서기본

In [2]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[1, 2],
                       [1, 2]])

c = torch.matmul(a, b)
c

tensor([[ 3.,  6.],
        [ 7., 14.]])

In [3]:
d = a@b
d

tensor([[ 3.,  6.],
        [ 7., 14.]])

In [4]:
a = torch.IntTensor([[1, 2],
                    [3, 4]])
a

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

IntTensor도 선언 가능하지만 일반적으로 딥러닝에서 가중치, 출력값, 손실. 기울기 등 모든 연산이 실수 연산  
그래서 FloatTensor를 기본으로 사용한다.

In [5]:
b = torch.LongTensor([[1, 2],
                       [1, 2]])

b

tensor([[1, 2],
        [1, 2]])

In [6]:
c = torch.ByteTensor([[1, 2],
                       [1, 2]])

c

tensor([[1, 2],
        [1, 2]], dtype=torch.uint8)

In [7]:
mask = torch.BoolTensor([True, False, True])

mask

tensor([ True, False,  True])

In [8]:
x = torch.FloatTensor(3, 2) # shape (3,2)인 텐서

x

tensor([[-1.3960e+11,  1.1070e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])

In [9]:
a = torch.zeros(3,2)    # (3,2) 0 로 채워진 텐서

a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [10]:
b = torch.ones(3,2)     # (3,2) 1 로 채워진 텐서
b

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
c = torch.randn(3,2)    # (3,2)정규분포 난수 텐서

c

tensor([[-0.6264, -0.8191],
        [-0.6516, -1.6993],
        [ 0.4748,  0.7154]])

In [12]:
import numpy as np

x = np.array([[1,2],
             [3,4]])
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [13]:
# Pytorch tensor로 변환

x = torch.from_numpy(x)

print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [14]:
# Pytorch Tensor를 Numpy ndarray 형태로 변환

x= x.numpy()

print(x,type(x))


[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [15]:
x = torch.from_numpy(x)

x.long()  #LongTensor(int64) 타입으로 변환. 소수점은 버림 ( 분류 문제 정답라벨)

tensor([[1, 2],
        [3, 4]])

In [16]:
print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [17]:
x.float()       #FloatTensor(float64) 타입으로 변환

print(x,type(x))


tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [18]:
torch.FloatTensor([1,0]).bool() #BoolTensor 타입으로 변환

tensor([ True, False])

In [19]:
x = torch.FloatTensor([[[1,2],[3,4]],
                       [[5,6],[7,8]],
                        [[9,10],[11,12]]])


print(x.size()) # Pytorch 메서드
print(x.shape)  # 넘파이에서 주로 사용

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [20]:
print(x.dim())  # 텐서의 차원 수 (3,2,2) -> 3개 차원

3


In [21]:
print(len(x.size()))    # 텐서의 길이 => 차원수

3


In [22]:
# 텐서의 특정 차원에 있는 요소의 개수
print(x.size(1))        # Pytorch 메서드 (1번 축 크기)
print(x.shape[1])       # numpy 스타일 (1번 축 크기)

2
2


In [23]:
# 마지막 차원에 있는 요소의 개수
print(x.size(-1))        # Pytorch 메서드 (마지막 축 크기)
print(x.shape[-1])       # numpy 스타일 (마지막 축 크기)

2
2


# 텐서 연산

In [24]:
import torch

a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[1, 2],
                       [1, 2]])

a+b

tensor([[2., 4.],
        [4., 6.]])

In [25]:
a -b

tensor([[0., 0.],
        [2., 2.]])

In [26]:
a *b

tensor([[1., 4.],
        [3., 8.]])

In [27]:
a /b

tensor([[1., 1.],
        [3., 2.]])

In [28]:
a == b

tensor([[ True,  True],
        [False, False]])

In [29]:
a != b

tensor([[False, False],
        [ True,  True]])

In [30]:
a ** b

tensor([[ 1.,  4.],
        [ 3., 16.]])

In [31]:
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [1., 2.]])


In [32]:
print(a.mul(b))

tensor([[1., 4.],
        [3., 8.]])


In [33]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [34]:
print(a.mul_(b))  # _가 붙은 연산은 원본 Tendsor를 바꿔주는 in-place 역할

tensor([[1., 4.],
        [3., 8.]])


In [35]:
print(a)

tensor([[1., 4.],
        [3., 8.]])


In [36]:
print(a.sum())      # 전체 합 
print(a.mean())     # 전체 평균

tensor(16.)
tensor(4.)


In [37]:
print(a.sum(dim=0)) # 행 축을 따라 값들을 더함 (행 축은 사라진다.)
print(a.sum(dim=1)) # 열 축을 따라 값들을 더함 (열 축은 사라진다.)

tensor([ 4., 12.])
tensor([ 5., 11.])


해당 dim 차원을 합치기 때문에 해당 축은 사라진다.

In [38]:
print(a.sum(dim=0).shape)
print(a.sum(dim=1).shape)

torch.Size([2])
torch.Size([2])


Broadcast : 텐서의 차원(크기)이 다를 때, 자동으로 차원을 확장해 차원을 맞춰주는 기능

In [39]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[4,8]])

print(x.shape,y.shape)

torch.Size([1, 2]) torch.Size([1, 2])


In [40]:
z = x+y
print(z,z.size())

tensor([[ 5., 10.]]) torch.Size([1, 2])


In [41]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

y = 1

print(x.shape)

torch.Size([2, 2])


In [42]:
z = x+y

print(z,z.shape)



tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


```
1 -> [[1, 1],
      [1, 1]]
```

x와 동일한 shape으로 브로드캐스팅 (자동 형변환)

In [43]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

y = torch.FloatTensor([3,5])

print(x.shape,y.shape)

torch.Size([2, 2]) torch.Size([2])


In [44]:
z= x + y 

print(z,z.shape)

tensor([[4., 7.],
        [6., 9.]]) torch.Size([2, 2])


```
[3,5] -> [[3,5],
          [3,5]]
```
x의 행 수만큼 복제

In [45]:
x = torch.FloatTensor([[[1, 2]]])

y = torch.FloatTensor([3, 5])

print(x.shape,y.shape)

torch.Size([1, 1, 2]) torch.Size([2])


마지막 차원수 2로 같기 떄문에 나머지 차원은 y에 없으므로 자동으로 1로 확장

In [46]:
z = x + y
print(z,z.size())

tensor([[[4., 7.]]]) torch.Size([1, 1, 2])


In [47]:
x = torch.FloatTensor([[1, 2]])

y = torch.FloatTensor([[3], [5]])

print(x.shape,y.shape)

torch.Size([1, 2]) torch.Size([2, 1])


In [48]:
z = x + y
print(z,z.size())

tensor([[4., 5.],
        [6., 7.]]) torch.Size([2, 2])


개수가 1인 차원은 확장된다.  
마지막 차원 2 와 1 -> 1이 확장되어 2  
앞 차원 1과 2 -> 1아 확장되어 2  

```
[[1, 2]] -> [[1, 2]
             [1, 2]]

[[3],   ->  [[3,3],
[5]]        [5,5]]


```

In [49]:
# 잘못 사용된 예시 
x = torch.FloatTensor([[[1, 2],
                       [4, 8]]])
y = torch.FloatTensor([[1, 2, 3], 
                       [4, 5, 5],
                       [7, 8, 9]])

print(x.shape,y.shape)

torch.Size([1, 2, 2]) torch.Size([3, 3])


In [50]:
# z = x+ y



0번 차원 : x는 1, y는 - => 자동 확장 가능  
1번 차원 : x는 2, y는 3 => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님  
2번 차원 : x는 2, y는 3 => 다른데, 하나라도 1이면 가능하지만 둘다 1이 아님  

브로드 캐스팅 조건 : 각 차원의 값이 같거나, 하나가 1일 경우에만 자동 확장 가능  

# 텐서 조작하기

In [51]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5,6],
                        [7,8]],
                        [[9,10],
                         [11,12]]])  # (3, 2, 2)

x.size()

torch.Size([3, 2, 2])

In [52]:
print(x.reshape(12))        # shape을 명시적으로 지정 (12개 요소를 가진 1차원 텐서)
print(x.reshape(-1))        # -1 : 자동 지정 (자동 지정되는 갯수의 요소를 가진 1차원 텐서)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [53]:
print(x.reshape(3,4))   # 3행 4열로 shape 재구성
print(x.reshape(3,-1))  # 동일
# print(x.reshape(8,-1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [54]:
print(x.reshape(3,1,4))     # 1행 4열 행렬 3개
print(x.reshape(-1,1,4))    # 동일
# print(x.reshape(-1,-1,4))    # 오류 발생 (자동 2개는 불가)


tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [55]:
print(x.reshape(3,2,2,1))   # 2행 2열 + 채널 1이 붙은 데이터 3개

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


In [56]:
print(x.view(3,2,2,1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


view() : 연속된 메모리 구조일때 사용  
reshape() : 필요시 데이터 복사도 가능한 유연한 재구성 함수

In [57]:
# squeeze() : 텐서에서 크기가 1인 차원 제거

x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])

print(x.shape)

torch.Size([1, 2, 2])


In [58]:
print(x.squeeze(),x.squeeze().size())   # squeeze : 차원을 줄임

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


In [59]:
# squeeze(차원) : 특정 차원을 제거. 크기가 1일 경우에만
print(x.squeeze(0).size()) 
print(x.squeeze(1).size()) 


torch.Size([2, 2])
torch.Size([1, 2, 2])


In [60]:
# unsqueeze() : 특정 위치에 새 차원을 추가

x = torch.FloatTensor([[1, 2],
                        [3, 4]])

x.size()

torch.Size([2, 2])

In [61]:
print(x.unsqueeze(2),x.unsqueeze(2).size())     # 2번 차원
print(x.unsqueeze(-1),x.unsqueeze(-1).size())    # 마지막 차원
print(x.reshape(2,2,-1),x.reshape(2,2,-1).shape) # 동일

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]]) torch.Size([2, 2, 1])


차원 조작 같은 경우 입력층 -> 은닉층 또는 은닉층 -> 출력층 부분에서   
차원을 맞춰서 값을 넘겨야 할 때 주로 사용한다.

# 텐서를 자르고 붙이기 (Indexing & Slicing)

In [62]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5,6],
                        [7,8]],
                        [[9,10],
                         [11,12]]])

x.size()

torch.Size([3, 2, 2])

In [63]:
print(x[0]) # 첫 번째 차원(dim = 0) 에서 인덱스 0 선택
print(x[0,:,:]) # 생략된 차원을 명시적으로 표시

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [64]:
print(x[0,:]) # 첫 번째 차원(dim = 0) 에서 두번쨰 차원 (dim = 1)을 선택

tensor([[1., 2.],
        [3., 4.]])


뒤쪽 차원의 : (전체선택)은 생략 가능하며, 생략하면 자동으로 : (전체선택) 차리된다.

In [65]:
print(x[-1]) # 마지막 차원(dim = 0) 에서 마지막 인덱스 0 선택
print(x[-1,:]) # 마지막 차원(dim = 0) 에서 두번쨰 차원 (dim = 1)을 : 전체 선택
print(x[-1,:,:])    # 생략된 차원을 명시적으로 표시

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [66]:
print(x[:,0,:],x[:,0,:].shape) # 전체 배치에서 첫번째 행만 가져옴 (열 전체)

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]) torch.Size([3, 2])


배치는 그대로 3 유지  
행은 선택되어 제거  
열은 그대로 2 유지

In [67]:
# 슬라이싱으로 접근시 차원 수 유지

print(x[1:3,:,:],x[1:3,:,:].shape)  # 배치 1, 2 선택, 행과 열은 전체

tensor([[[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]]) torch.Size([2, 2, 2])


In [68]:
print(x[:,:1,:],x[:,:1,:].size())   # 모든 배치. 행은 앞의 1개만 슬라이싱, 열은 전체

tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]]) torch.Size([3, 1, 2])


In [69]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [70]:
# 모든 배치에 행은 마지막 행제외, 열은 전체
print(x[:,:-1,:],x[:,:-1,:].size())

tensor([[[ 1.,  2.]],

        [[ 5.,  6.]],

        [[ 9., 10.]]]) torch.Size([3, 1, 2])


In [71]:
# split() : 텐서를 원하는 모양으로 나눠준다.
x = torch.zeros(10, 4)
# x = torch.FloatTensor(10,4)

x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [72]:
splits = x.split(4, dim=0)  # 0번 차원 기준으로 4개씩 자름
splits

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [73]:
print(type(splits))


<class 'tuple'>


In [74]:
for i , split in enumerate(splits):
    print(i+1,split.size())

1 torch.Size([4, 4])
2 torch.Size([4, 4])
3 torch.Size([2, 4])


In [75]:
# chunk() : 텐서를 청크 수로 나눈다.  
x = torch.ones(8,4)

chunks = x.chunk(4, dim =0) # 0번 차원 기준으로 3 조각으로 나눔

for chunk in chunks:
    print(chunk.size())
chunks

torch.Size([2, 4])
torch.Size([2, 4])
torch.Size([2, 4])
torch.Size([2, 4])


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

split(n) : n개로 균등하게 분할 (크기)  (리스트나 튜플로도 가능)  
chunk(size) : size만큼 조각하여 자른다 (개수) 

In [76]:
# index_select() : 차원 인덱스를 사용하여 요소를 선택

x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5,6],
                        [7,8]],
                        [[9,10],
                         [11,12]]])

indice = torch.LongTensor([2,1])

x.size()

torch.Size([3, 2, 2])

In [77]:
y = x.index_select(dim = 0 , index = indice)    # 0번 차원 indice에서 지정한 순서대로 선택
                                                # [2,1] -> x[2], 그다음 x[1]
print(y,y.size())

tensor([[[ 9., 10.],
         [11., 12.]],

        [[ 5.,  6.],
         [ 7.,  8.]]]) torch.Size([2, 2, 2])


index_select 함수는 반환값이 있어 텐서가 새로 생성되어 사용시 값으로 받아준다.  
index는 LongTensor형태로 전달해준다.

In [78]:
x.index_select(0 , index = torch.LongTensor([0,0])) # 인덱스 중복 선택 x[0,:,:],x[0,:,:]

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])

In [79]:
# cat() : 여러 텐서간에 연결

x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

print(x.size(),y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [80]:
z = torch.cat([x,y],dim = 0)    # ㅎdim = 0 : 0번차원 (행 방향) 으로 이어 붙임

print(z,z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]) torch.Size([6, 3])


cat으로 붙이는 축을 제외한 나머지 차원은 반드시 동일해야 이어 붙일 수 있다.  
2차원 Tensor 기준 dim = 0 : 행 증가  
2차원 Tensor 기준 dim = 1 : 열 증가  

In [81]:
z = torch.cat([x,y],dim = 1)

print(z,z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]]) torch.Size([3, 6])


In [82]:
# stack() : 여러 텐서를 쌓아 새로운 차원을 만든다.

z = torch.stack([x,y])      # x, y 2차원 데이터를 2장 쌓아 (2,3,3) 형태로 만듬
print(z,z.size()) 

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]]) torch.Size([2, 3, 3])


cat() : 차원 수 동일. 기존 축에 그대로 이어 붙임  
stack() : 차원 수 +1. 새로운 축을 만들어 쌓음

In [83]:
print(torch.cat([x,y]).size())

print(torch.stack([x,y]).size())

torch.Size([6, 3])
torch.Size([2, 3, 3])


In [84]:
z = torch.stack([x,y],dim = -1) # 마지막 차원 추가 (feature, channel 차원)

print(z,z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]]) torch.Size([3, 3, 2])


In [85]:
# cat() 과 unsqueeze() 사용하여 stack 구현하기

z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)],dim = 0)

print(z,z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]]) torch.Size([2, 3, 3])


In [86]:
# 빈복문 결과를 하나로 병합해보기 (2,2) -> (5,2,2). 배치 데이터 생성시 사용

result = []
for i in range(5):
    x = torch.FloatTensor(2,2)
    result += [x]   # (2,2) 텐서를 리스트에 하나씩 추가

result = torch.stack(result)    # 리스트 텐서들을 새로운 차원으로 쌓음
result.size()

torch.Size([5, 2, 2])

# Pytorch 메서드

In [87]:
# expand() : 크기가 1인 차원을 지정된 크기만큼 확장.

x = torch.FloatTensor([[[1,2]],
                       [[3,4]]])

print(x.shape)

torch.Size([2, 1, 2])


In [88]:
y = x.expand(*[2,3,2])  # 기존 (2,1,2) 에서 행 차원을 1 -> 3. 나머지 차원은 그대로 유지

print(y,y.shape)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


expand() : 값을 복사하지는 않는다. 내부적으로 같은 메모리를 여러 번 참조해서 사용
- 메모리 효율성이 높다.

값 앞에 '*'(unpacking)은 list나 tuple형 데이터를 순차적으로 전달하기 위해 사용

In [89]:
# cat을 활용하여 expand 구형하기

y = torch.cat([x,x,x],dim = 1) # dim=1(두번쨰 차원) 기준으로 x를 3번 이어붙임

print( y,y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]]) torch.Size([2, 3, 2])


In [90]:
# randperm(n) : 랜덤 순열 , 0부터 n-1까지의 정수를 무작위로 섞은 순열 텐서를 반환(특징 : 중복없음)
x = torch.randperm(10)

print(x,x.size())

tensor([3, 6, 0, 1, 2, 7, 4, 5, 9, 8]) torch.Size([10])


In [92]:
x = torch.randperm(3**3).reshape(3,3,-1)

print(x,x.size())

tensor([[[ 8, 10,  2],
         [12,  4, 25],
         [ 1,  3, 23]],

        [[ 7,  0, 24],
         [17, 18, 19],
         [16,  6, 26]],

        [[11, 14, 13],
         [20, 22, 15],
         [ 9, 21,  5]]]) torch.Size([3, 3, 3])


In [102]:
# argmax() : 최대값 인덱스 반환

y = x.argmax(dim=-1)    # a마지막 차원(열)에서 가장 큰 값의 인덱스를 반환하고, 그 차원은 제거

print(y,y.size())

tensor([[1, 2, 2],
        [2, 2, 2],
        [1, 1, 1]]) torch.Size([3, 3])


argmax(dim = k) : k번 차원에서 가장 큰 인덱스를 선택하고, 그차원 제거

In [ ]:
y = x.argmax(dim=-1,keepdim=True)    # a마지막 차원(열)에서 가장 큰 값의 인덱스를 반환하고, 그 차원은 제거

print(y,y.size())

tensor([[[1],
         [2],
         [2]],

        [[2],
         [2],
         [2]],

        [[1],
         [1],
         [1]]]) torch.Size([3, 3, 1])


In [ ]:
# topk() : 상위 k개의 값과 해당 인덱스를 튜플로 반환




topk(k=1)로 설정하면 argmax(keepdim = True)와 같은 결과

In [108]:
# topk를 이용해 정렬하기
target_dim = -1
values, indices = torch.topk(
    x,
    k=x.size(target_dim),   # 마지막 차원의 전체 길이
    largest= True           # 큰 값부터 선택
)

print(values,values.size())
print(indices,indices.size())

tensor([[[10,  8,  2],
         [25, 12,  4],
         [23,  3,  1]],

        [[24,  7,  0],
         [19, 18, 17],
         [26, 16,  6]],

        [[14, 13, 11],
         [22, 20, 15],
         [21,  9,  5]]]) torch.Size([3, 3, 3])
tensor([[[1, 0, 2],
         [2, 0, 1],
         [2, 1, 0]],

        [[2, 0, 1],
         [2, 1, 0],
         [2, 0, 1]],

        [[1, 2, 0],
         [1, 0, 2],
         [1, 0, 2]]]) torch.Size([3, 3, 3])


x[i, j, :]을 큰 값 기준으로 내림차순 정렬
- 차원 수는 그대로 유지. 값의 순서만 바뀜 (정렬)
- 각 줄에서는 큰값 -> 작은 값 순으로 정렬

indices는 정렬되기 전 위치 값

결과적으로 topk(k=차원 크기)를 주면 해당 차원을 기준으로 값을 정렬한 효과를 얻는다.

In [110]:
k =1 
values, indices = torch.sort(x,dim=-1,descending=True)  # 마지막 차원을 기준으로 내림차순 정렬(값,원래위치)
values,indices = values[:,:,:k],indices[:,:,:k] # 정렬된 결과 중 가장 큰값 1개 선택 (3,3,1)

print(values.squeeze(-1),values.squeeze(-1).size())   # (3,3,1) -> (3,3)
print(indices.squeeze(-1),indices.squeeze(-1).size())  # (3,3,1) -> (3,3)

tensor([[10, 25, 23],
        [24, 19, 26],
        [14, 22, 21]]) torch.Size([3, 3])
tensor([[1, 2, 2],
        [2, 2, 2],
        [1, 1, 1]]) torch.Size([3, 3])


sort+ 슬라이싱 = topk 사용과 동일한 효과를 얻는다.

In [119]:
# masked_fill() : 마스크가 True인 위치에 지정한 값을 채움
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x, x.size())


tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) torch.Size([3, 3])


In [120]:

torch.FloatTensor([i for i in range(3**2)]).reshape(1, 1, -1).size()    # 1, 1, 9 (-1은 자동계산)

torch.Size([1, 1, 9])

In [121]:
mask = x > 4

mask
y = x.masked_fill(mask, value = -1)     # mask가 True인 위치를 -1로 채움 

print(y, y.size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]]) torch.Size([3, 3])


masked_fill 사용처
- 이미지 처리 padding 처리
- loss 계산에서 해당 값 무시
<!-- - attention mask -->

In [ ]:
# ones(), zeros() : 모든 요소가 0 또는 1로 채워진 텐서 반환
print(torch.ones(2,3))
print(torch.zeros(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [114]:
print(x.size(),y.size())

torch.Size([3, 3, 3]) torch.Size([3, 3])


In [115]:
# ones_like(), zeros_like() : 기준 텐서와 동일한 형태의 초기화 텐서 반환
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])
tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])
